### ISSUE TITLE
[iOS] Norton360's SafeWeb feature misleads jailbreak checks.

### ISSUE THREAD

**Issue by saito-tk** [w3connext/jailbreak_root_detection#2]
For iOS devices, when the SafeWeb feature of the Norton360 app is turned on, the isJailBroken flag is true.

SafeWeb ON Result:
isNotTrust: true
isRealDevice: true
isJailBroken: true
isTampered: false

SafeWeb OFF Result:
isNotTrust: false
isRealDevice: true
isJailBroken: false
isTampered: false

**Comment by saito-tk** [comment]
I found that the amProxied flag in [checkJailBroken()](https://github.com/w3connext/jailbreak_root_detection/blob/3bddc198ca3c32fda79af977e93b3f280bcb1cd6/ios/Classes/JailbreakRootDetection.swift#L13C10-L29) is affected by Norton360's SafeWeb.

**Comment by acacioveit** [comment]
I'm facing the same here @saito-tk

**Comment by acacioveit** [comment]
@saito-tk I've submitted [this PR](https://github.com/w3connext/jailbreak_root_detection/pull/3) which bring the `checkForIssues` method, so it will return a `List<JailbreakIssue>` then you can check this list to fullfill your usecase.

**Comment by saito-tk** [comment]
@acacioveit 
Thanks for the correction!
I will give it a try.
